# Generated by Django 3.0.5 on 2021-07-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
